# Generated by Django 5.0.6 on 2024-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carbrand_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='view_count_day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='view_count_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='view_count_week',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
