# Generated by Django 5.0.6 on 2024-08-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_carmodel_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='exchange_rate_eur',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='exchange_rate_usd',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price_uah',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
