# Generated by Django 5.0.6 on 2024-07-03 07:25

import core.services.upload_photo
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('year', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, upload_to=core.services.upload_photo.upload_photo, validators=[django.core.validators.FileExtensionValidator(['gif', 'jpeg', 'png'])])),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
