# Generated by Django 5.0.6 on 2024-07-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carmodel_exchange_rate_eur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
