# Generated by Django 5.0.6 on 2024-07-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carbrand_alter_carmodel_brand_carbrandmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carbrand',
            table='car_brands',
        ),
    ]
