# Generated by Django 5.0.6 on 2024-07-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='account_type',
            field=models.CharField(choices=[('basic', 'Базовий'), ('premium', 'Преміум')], default='basic', max_length=10),
        ),
    ]
